# Generated by Django 4.0.3 on 2022-03-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Created_time',
            new_name='created_time',
        ),
    ]
